package com.mycorp.dsl

import kotlin.reflect.KClass

/**
 * Marker interface used by the generated stub auto-generated by KSP.
 */
interface WorkerDescriptor<A: IO, B: IO> {
    val name: String
    val type: KClass<out Worker<*, *>>
    val inputType: KClass<*>
    val outputType: KClass<*>
}